name: Purchase Status Notification Sender
on:
  push:
    branches:
      - main
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam validate
      - run: sam build
      - name: Install npm modules
        run: cd app && npm install && cd ..
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env prod